name: ⛅ CF Worker
on:
  # docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  # docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
  # docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:
    # github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    # docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
    inputs:
      # docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
      environment:
        description: 'wrangler env to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
        - dev
        - prod
        - one
      commit:
        description: 'git tip commit to deploy'
        default: 'main'
        required: true

env:
  GIT_REF: ${{ github.event.inputs.commit || github.ref }}
  # default is 'dev' which is really empty/no env
  WORKERS_ENV: ''

jobs:
  deploy:
    name: 🚀 Deploy worker
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.0.0'  # 指定 Node.js 版本
      - run: npm ci
      - run: npm run build --if-present
      - name: 🛸 Env?
        # 'dev' env deploys to default WORKERS_ENV, which is, '' (an empty string)
        if: github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'one'
        run: |
          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
        shell: bash
        env:
          WENV: ${{ github.event.inputs.environment }}
          COMMIT_SHA: ${{ github.sha }}

      - name: 🎱 Tag?
        # docs.github.com/en/actions/learn-github-actions/contexts#github-context
        if: github.ref_type == 'tag'
        run: |
          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
        shell: bash
        env:
          # tagged deploys always deploy to prod
          WENV: 'prod'
          COMMIT_SHA: ${{ github.sha }}

        # npm (and node16) are installed by wrangler-action in a pre-job setup
      - name: 🏗 Get dependencies
        run: npm i

      - name: 📚 Wrangler publish
        # github.com/cloudflare/wrangler-action
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # input overrides env-defaults, regardless
          environment: ${{ env.WORKERS_ENV }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GIT_COMMIT_ID: ${{ env.GIT_REF }}

      - name: 🎤 Notice
        run: |
          echo "::notice::Deployed to ${WORKERS_ENV} / ${GIT_REF} @ ${COMMIT_SHA}"
